### ISSUE TITLE
rob contrib?

### ISSUE THREAD

**Issue by robfatland** [pangeo-data/education-material#3]
Paul might it make sense to make me a contributor on this repo so I can just hack away on the various README files? Otherwise happy to stay with the PR plan, no prob.

**Comment by rabernat** [comment]
@robfatland - I just made you an owner here.

PRs are still good if you're looking for feedback.

**Comment by kmpaul** [comment]
Thanks, @rabernat!

I added _some_ of the people who contributed to pangeo-data/pangeo#575 as a contributor to this repo.  If you want to be added, just let me know.
